### ISSUE TITLE
Is the CString need to be freed?

### ISSUE THREAD

**Issue by yutannihilation** [r-rust/hellorust#10]
This is rather a question. During exploring how to handle vectors, I found I needed to pass back the vector to Rust to deallocate it if it's allocated by Rust. I'm wondering if this `CString` should be freed in the same way otherwise this stays on memory forever, right...? 

https://github.com/r-rust/hellorust/blob/68d2b2b4477c5c929c1a88c6ebfae11c2e6502a1/src/myrustlib/src/hello.rs#L7

**Comment by jeroen** [comment]
Can you send a PR?

**Comment by yutannihilation** [comment]
After thinking this issue again after 3 years, I have no idea what to do. Let me check if my understanding is correct.

* `CString::new()` does allocate (right?), so it needs to be freed on Rust's side.
* This C string needs to live until `Rf_mkCharCE()` is called, and be freed then.
* But, since `Rf_mkCharCE()` is called on C's side, we cannot free it there because C and Rust might use different allocators.
* So, we need another Rust function dedicated for freeing it by bringing the forgotten pointer back to `CString()` (`CString::from_raw()`).

Does this sound good? Honestly, I feel this is a bit advanced and might not suitable for an example package. So, accepting memory leak might be an option here (but, I think this should be explained in the code comments at least).
