### ISSUE TITLE
Shortcut around CRAN rules if possible 

### ISSUE THREAD

**Issue by nfultz** [r-rust/hellorust#14]
There's some logic to re-download all cargo deps for CRAN in `Makevars`. I saw the comment about commenting it out, but would be nice to add a 

```
ifdef NOTCRAN
  # fast
else 
   #slow
endif
```

around it. iirc `testthat` does a similar trick.

**Comment by eitsupi** [comment]
How about this? extendr/rextendr#233

**Comment by nfultz** [comment]
They say great minds think alike :)
