### ISSUE TITLE
Addresses "If running a package uses multiple threads/cores it must never use more than two simultaneously"

### ISSUE THREAD

**Issue by eitsupi** [r-rust/hellorust#18]
<https://cran.r-project.org/web/packages/using_rust.html> says:

> cargo build -j N defaults to the number of ‘logical CPUs’. This usually exceeds the maximum allowed in the CRAN policy, so needs to be set explicitly to N=1 or 2. 

The easy way to deal with this seems to be to set `CARGO_BUILD_JOBS=2` in the Makevars file. (eitsupi/prqlr#151)

**Comment by jeroen** [comment]
Thanks!
