### ISSUE TITLE
Installation issure

### ISSUE THREAD

**Issue by o1iv3r** [r-rust/hellorust#8]
Hi,
when trying to install with devtools::install_github() I receive the following error:

>    Compiling libc v0.2.73
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-pc-windows-gnu` target may not be installed

Rust is installed and hello world runs.

Thank you,
Oliver

**Comment by jeroen** [comment]
Did you install both the 32-bit and 64-bit rust targets?

**Comment by o1iv3r** [comment]
Thanks for the quick reply!
I think so... this is the version I see on cmd: stable-x86_64-pc-windows-msvc unchanged - rustc 1.45.0 (5c1f21c3b 2020-07-13)

**Comment by jeroen** [comment]
You need to `gnu` targets, not msvc, see the readme.

**Comment by o1iv3r** [comment]
Sorry... new to Rust. Thank you!
